using Microsoft.EntityFrameworkCore.Migrations;

namespace Common.Migrations
{
    /// <summary>
    /// Contains the Up and Down methods for the migrations that have additional elements beyond
    /// those generated by Entity Framework
    /// </summary>
    public static class ManualMigrations
    {
        public static void Foo_Up(this MigrationBuilder migrationBuilder)
        {
            _ = migrationBuilder;
            
            // TODO...
        }

        public static void Foo_Down(this MigrationBuilder migrationBuilder)
        {
            _ = migrationBuilder;

            // TODO...
        }
    }
}
